;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters=
+GameplayTagTableList=/Game/Blueprints/AbilitySystem/GameplayTags/DT_MessageTags.DT_MessageTags
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Montage.BlazingFlame",NewTagName="Event.Montage.Fire.BlazingFlame")
+GameplayTagRedirects=(OldTagName="Event.Montage.FallOfTheScorchingSun",NewTagName="Event.Montage.Fire.FallOfTheScorchingSun")
+GameplayTagRedirects=(OldTagName="Event.Montage.IgnitionLeap",NewTagName="Event.Montage.Fire.IgnitionLeap")
+GameplayTagRedirects=(OldTagName="Event.Montage.PiercingMagma",NewTagName="Event.Montage.Fire.PiercingMagma")
+GameplayTagRedirects=(OldTagName="Event.Montage.RisingFlameWave",NewTagName="Event.Montage.Fire.RisingFlameWave")
+GameplayTagRedirects=(OldTagName="Event.Montage.SearingFlame",NewTagName="Event.Montage.Fire.SearingFlame")
+GameplayTagList=(Tag="Event.Montage.Fire.BlazingFlame",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire.FallOfTheScorchingSun",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire.IgnitionLeap",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire.PiercingMagma",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire.RisingFlameWave",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Fire.SearingFlame",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Water.SimpleIce",DevComment="")
+GameplayTagList=(Tag="Event.MotionWarping.Stop",DevComment="")

